pub mod chunk;
pub mod cluster;
pub mod config;
pub mod embedder;
pub mod error;
pub mod macros;
pub mod mcp;
pub mod parser;
pub mod search;
pub mod store;
pub mod summarizer;

pub use chunk::{ChunkLevel, ClusterMembership, HierarchicalChunk};
pub use cluster::{ClusterPipeline, SoftClusterer};
pub use config::Config;
pub use embedder::Embedder;
pub use error::{Error, Result};
pub use parser::DocumentParser;
pub use search::HierarchicalSearch;
pub use store::VectorStore;
pub use summarizer::{OllamaSummarizer, Summarizer};
